### PR TITLE
ADCM-1839 Added `logout()` method for ADCMClient

### PR DESCRIPTION
**Pull request by a-alferov**

### CODE REVIEW

**Comment by dgusakov** [comment]
@a-alferov looks like logout method makes makes sense for UI only
`from adcm_client.objects import ADCMClient
adcm = ADCMClient(url="http://localhost:8004", user="admin", password="admin")
adcm.cluster_list()
Out[4]: [<Cluster Pre-uploaded cluster for the import form bundle - 3 at 4497811152>, <Cluster Pre-uploaded cluster with services form bundle - 4 at 4515540800>, <Cluster KSJpxdEmRU form bundle - 5 at 4497708128>]
adcm.logout()
adcm.cluster_list()
Out[6]: [<Cluster Pre-uploaded cluster for the import form bundle - 3 at 4515537488>, <Cluster Pre-uploaded cluster with services form bundle - 4 at 4515538832>, <Cluster KSJpxdEmRU form bundle - 5 at 4515540080>]`

**Comment by a-alferov** [comment]
@dgusakov Yes you are right. The client cannot work without a schema, and authentication is required to obtain it.

**Comment by dgusakov** [comment]
> The client cannot work without a schema, and authentication is required to obtain it.
You mean that if we call `adcm.logout()` new authorisation will be performed in `adcm.cluster_list()`?

**Comment by a-alferov** [comment]
No, the client is authorizing when creating the ADCMClient object using a token, not a session

**Review by dgusakov — CHANGES_REQUESTED** [review]
I guess such logout implementation makes no sense

**Comment by a-alferov** [comment]
It does not work properly

**Pull request closed without merging**
